### PR TITLE
Update es_es.json

### PR DESCRIPTION
**Pull request by Ismasan99**
Translated everything from last en_en.json to es_es.jso
[forbidden_es.zip](https://github.com/stal111/Forbidden-Arcanus/files/9191371/forbidden_es.zip)

### CODE REVIEW

**Comment by stal111** [comment]
Thanks for the effort. However, this pull request seems a bit messed up, do you know how pull requests work? You want to merge one branch into the main 1.18 one which is completely unrelated to the translation. 

Would be awesome if you could open a new correct pull request on the 1.19 branch that also directly adds the new translation, not only including it in the description, as that would save me some time.

**Comment by Ismasan99** [comment]
Okay, think I did on the correct way the pull request. Could you confirm please? Kind of new to github. Thanks!

**Comment by stal111** [comment]
You've created a fork of the repository now and added your changes there. As last step you will need to open a new pull request that merges your Translation_es branch into the main 1.19 one here.

**Comment by Ismasan99** [comment]
okay thinks is done

**Pull request closed without merging**
